// <auto-generated />
using Mango.Services.Coupon.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.Coupon.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.Coupon.API.Models.Coupons", b =>
                {
                    b.Property<int>("CounponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounponId"));

                    b.Property<string>("CounponCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("DiscountAmmount")
                        .HasColumnType("float");

                    b.Property<int>("MinAmmount")
                        .HasColumnType("int");

                    b.HasKey("CounponId");

                    b.ToTable("coupons");

                    b.HasData(
                        new
                        {
                            CounponId = 1,
                            CounponCode = "100FF",
                            DiscountAmmount = 10.0,
                            MinAmmount = 20
                        },
                        new
                        {
                            CounponId = 2,
                            CounponCode = "200FF",
                            DiscountAmmount = 10.0,
                            MinAmmount = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
